language: node_js
os: windows
node_js:
  - "lts/*"

after_success: 
  - npm run coveralls

before_deploy: 
  - npm run build

deploy:
  provider: npm
  email : $NPM_EMAIL
  api_token: $NPM_TOKEN
  edge: true
  access: public
  cleanup: false
  on:
    branch: master
    tags: true
